feat: ✨ Add count endpoint
Blagues-API/blagues-api.fr pull request #53
Opened 2022-06-25 00:46 UTC by Swiizyy

2022-06-25 21:48 UTC, DraftProducts requested changes

2022-06-25 21:48 UTC, DraftProducts commented on components/doc/Packagist.vue
> +            composer require zuruuh/blagues-api
Il faudrait voir s'il y aurait moyen de faire comme avec npm & pypi d'avoir un nom unique dans le prefix de l'user étant donné que le module fait à présent partie de manière officielle du projet.

2022-06-25 21:48 UTC, DraftProducts commented on components/home/Hero.vue
> +          </button>
À voir comment ça rend, j'ai peur du rendu, l'espace n'avait pas été calculé pour avoir un nouvel élément, il faudra peut-être revoir le design de cet espace pour le permettre proprement 🤔

2022-06-25 21:48 UTC, DraftProducts commented
En tout cas gros gg pour le taff effectué 👍

2022-06-25 22:26 UTC, Zuruuh commented on components/doc/Packagist.vue
> +            composer require zuruuh/blagues-api
La seule vraie solution que je vois pour pas casser tous les projets existants c'est juste de déprécier le paquet existant sur packagist et d'en créer un nouveau (genre "blagues-api/blagues-api")

2022-06-25 22:29 UTC, Zuruuh commented on components/home/Hero.vue
> +          </button>
On a ducoup ajouté un wrap sur les buttons et je sais pas si t'as pu voir le rendu mais ça rends assez bien au final. Ptet une modif a faire serait de remplacer le texte dans le button par "PHP" au lieu de "PACKAGIST" car il prends pas mal de place. Concernant un redesign je pense pas que soit nécessaire, le bouton s'intègre plutôt bien avec les autres (on a testé avec tous les breakpoints :+1: ).

2022-06-25 23:20 UTC, DraftProducts commented on components/home/Hero.vue
> +          </button>
Yes je viens de voir 
![image](https://user-images.githubusercontent.com/29425008/175793291-c87dc990-c8f5-460c-b085-2906505ef7b9.png)

Mise à part l'espacement qui devrait être le même que celui entre les boutons je disais à Swiizyy en mp que c'était beaucoup plus clean que ce que j'avais imaginé.

2022-06-25 23:22 UTC, DraftProducts commented on components/doc/Packagist.vue
> +            composer require zuruuh/blagues-api
Yes si on le move, il faudra le déprécier c'est sûr, mais t'es sûr qu'on est obligé d'avoir un auteur ?
On ne peut pas juste le publier en `blagues-api` ?

2022-06-25 23:24 UTC, Zuruuh commented on components/home/Hero.vue
> +          </button>
Nickel, pour l'espacement on a fait un truc un peu à la va-vite avec tous les boutons qui ont la même margin-top mais après réflexion on aurait pu mettre la même margin top que sur la margin right (on a gardé 24px au top car c'était la valeur déjà utilisé avant pour le conteneur de boutons)

2022-06-25 23:28 UTC, Zuruuh commented on components/doc/Packagist.vue
> +            composer require zuruuh/blagues-api
nop, c'est comme ça sur packagist, le seul moyen d'avoir un package sans vendor devant c'est d'utiliser un outil comme symfony-flex, seul soucis c'est que:

1 - C'est pas framework agnostic (ça fonctionnera pas avec laravel ou cakephp)
2 - Symfony flex c'est juste un outil qui permet de créer des alias pour des packages (donc techniquement tu pourrais faire un ``composer require blagues-api`` mais dans ton composer.json à la fin ce sera qd même ``blagues-api/blagues-api``) donc c'est pas forcément utile

2022-06-25 23:30 UTC, DraftProducts commented on components/doc/Packagist.vue
> +            composer require zuruuh/blagues-api
Alors c'est pas la peine, autant laisser ton pseudo devant, je trouve ça à la limite plus propre que `blagues-api/blagues-api` 👍

2022-06-25 23:30 UTC, DraftProducts commented on components/home/Hero.vue
> +          </button>
Nickel alors 👍

2022-06-26 00:12 UTC, DraftProducts approved these changes

2022-06-28 01:18 UTC, merged