feat: :sparkles: QOL Changes
Blagues-API/blagues-api.fr pull request #55
Opened 2022-06-26 00:50 UTC by Zuruuh

See #54

2022-06-26 10:12 UTC, DraftProducts requested changes
Si tu tiens à le permettre sans docker faudra faire une mini documentation dans le readme ou autre fichier markdown (tout en le déconseillant)

2022-06-26 10:12 UTC, DraftProducts commented on .nvmrc
> +v16.15.1
Faudrait changer la version dans les deux fichiers Docker alors.

2022-06-26 10:12 UTC, DraftProducts commented on nuxt.config.js
> +import 'dotenv/config'
Je sais que c'est inutile dans Docker parce qu'il charge l'env depuis docker-compose à voir si on peut le supprimer pour la version sans.

2022-07-02 11:53 UTC, DraftProducts requested changes

2022-07-02 11:53 UTC, DraftProducts commented on components/doc/Packagist.vue
> +      </p>
Il n'y a pas un module pkgist plutôt qu'un module npm ?

2022-07-02 12:33 UTC, DraftProducts approved these changes

2022-07-02 12:39 UTC, Swiizyy commented
@DraftProducts Pour la doc sur le readme il ne manque rien ? c'est bon comme ca ? 🤔
Je t'ajouts que c'est pas la journée ou je suis le plus en forme mdr 😅

2022-07-02 14:02 UTC, DraftProducts commented
LGTM 🚀

2022-07-02 14:03 UTC, merged