docs: 📝 Update documentation for php lib v2.0.0
Blagues-API/blagues-api.fr pull request #71
Opened 2023-07-12 17:33 UTC by Zuruuh

J'ai pas mal mis a jour la lib php (mise à jour de la version minimale de php, update des deps, gestion du http client (c'est relou en php)), j'attends juste que ce soit bon pour vous pour release :+1:

2023-07-12 23:21 UTC, DraftProducts commented
Salut @Zuruuh 👋 
C'est cool que t'ai pu faire ce refactor et cette nouvelle version.
J'ai vu ton refactor sur la branche `dev` du repo du module php. Je n'ai pas encore vu de PR mais je suppose que c'est à venir.

Pour ce qui est de l'appelation du module (ou nom du namespace), j'ai vu que tu y avais mis ton pseudo, penses-tu que ce serait envisgeable d'en faire abstraction afin de ne laisser apparant que le nom du projet ? (`Blagues-API` adapté selon la case conventionnelle d'appellation).
Comme alternative, je te propose de faire un fichier CODEOWNERS en plus du contenu du champ "authors" présent dans le fichier composer.json.

2023-07-13 00:14 UTC, Zuruuh commented
J'ai crée la pr dcp https://github.com/Blagues-API/blagues-api-php/pull/17

> Pour ce qui est de l'appelation du module (ou nom du namespace), j'ai vu que tu y avais mis ton pseudo, penses-tu que ce serait envisgeable d'en faire abstraction afin de ne laisser apparant que le nom du projet ? (Blagues-API adapté selon la case conventionnelle d'appellation).   

Yes, j'ai ajouté mon pseudo histoire de mieux respecter la convention `namespace/package` plutot que juste un namespace "Blagues" qui faisait pas trop sens; mais je peux update pour un namespace "global" `BlagueApi` pour que ce soit plus clean

Puis sinon je vais check pr le codeowners et je t'ajouterais sur le authors du composer.json :+1:

2023-07-13 07:32 UTC, DraftProducts commented
Pour le namespace, je dirais `BlaguesApi` pour respecter l'orthographe du projet.
Sinon pour le authors du fichier composer, je n'y ai pas participé donc ce n'est pas la peine, tous les crédits te reviennent :v:

2023-07-13 07:36 UTC, DraftProducts requested changes

2023-07-13 07:36 UTC, DraftProducts commented on components/doc/Packagist.vue
> +          use Zuruuh/BlaguesApi\Model\Joke;
```suggestion
          use BlaguesApi\Factory\BlaguesApiFactory;
          use BlaguesApi\Model\Joke;
```

2023-07-13 07:36 UTC, DraftProducts commented on components/doc/Packagist.vue
> +          $blaguesApi = BlaguesApiFactory::create('<mark>VOTRE_TOKEN_ICI</mark>');
Je ne connais pas du tout la tech stack utilisé, donc c'est très probable que ça ne soit pas possible ou recommandé.
L'ajout du keyword Facrory est-il nécessaire ?
Ne pourrions-nous pas avoir simplement `$blaguesApi = BlaguesApi::create('token');` ?

2023-07-13 09:24 UTC, Zuruuh commented on components/doc/Packagist.vue
> +          $blaguesApi = BlaguesApiFactory::create('<mark>VOTRE_TOKEN_ICI</mark>');
Techniquement on pourrais, j'ai crée une factory a à coté pour gérer toute la partie concernant les dépendances mais c'est envisageable de bouger tout ça dans la classe de base

2023-07-13 10:05 UTC, DraftProducts approved these changes

2023-07-13 11:09 UTC, Swiizyy approved these changes

2023-07-14 15:52 UTC, merged